### ISSUE TITLE
Any fully open source game using this lib?

### ISSUE THREAD

**Issue by taisel** [threerings/clyde#11]
I'd rather give a helping hand to assist in updating it, but I need a reference to build it with.

I'm interested in looking into placing individual models & bounds checking in separate threads, and possibly improve some backing store usage.

**Comment by samskivert** [comment]
Not that I know of. The library was written concurrently with Spiral Knights, but I don't know of any open source game that uses it. Maybe someone else will pipe up here, but I wouldn't hold my breath.
